main: work.alsace.alsacecore.AlsaceCore
name: AlsaceCore
authors:
  - 'PuddingKC'
  - 'Hanamizu_'
  - 'CHuNan'
version: '1.0.1'
description: 阿尔萨斯工业基础插件
api-version: '1.16'
commands:
  fly:
    description: 设置自己或指定玩家的飞行状态
  speed:
    description: 设置自己或指定玩家的移动速度
  gamemode:
    description: 设置自己或指定玩家的游戏模式
    aliases:
      - 'gm'
  weather:
    description: 设置所在世界的天气
  time:
    description: 设置所在世界或指定世界的时间
  ptime:
    description: 设置自己或指定玩家的客户端时间
  tp:
    description: 传送到指定玩家或坐标
  tpignore:
    description: 忽略传送请求
  home:
    description: 传送到指定家
  sethome:
    description: 设置家
  delhome:
    description: 删除家
  hat:
    description: 戴上手上的物品
  head:
    description: 获取指定玩家的皮肤头颅
  warp:
    description: 传送到指定传送点
  delwarp:
    description: 删除传送点
  setwarp:
    description: 设置传送点
  night:
    description: 获取永久夜视效果
    aliases:
      - 'n'
  /twist:
    description: 快捷执行创世神deform指令
  /scale:
    description: 快捷执行创世神deform指令