main: work.alsace.alsacecore
name: AlsaceCore
author:
  - 'PuddingKC'
  - 'Hanamizu_'
  - 'CHuNan'
version: '1.0.1'
description: 阿尔萨斯工业基础插件
api-version: '1.16'
commands:
  fly:
    description: 设置自己或指定玩家的飞行状态
  speed:
    description: 设置自己或指定玩家的移动速度
  gamemode:
    description: 设置自己或指定玩家的游戏模式
    aliases:
      - 'gm'
  weather:
    description: 设置所在世界的天气
  time:
    description: 设置所在世界或指定世界的时间
  ptime:
    description: 设置自己或指定玩家的客户端时间
permissions:
  alsace.commands.fly:
    default: op
  alsace.commands.fly.other:
    default: op
  alsace.commands.speed:
    default: op
  alsace.commands.speed.other:
    default: op
  alsace.commands.gamemode:
    default: op
  alsace.commands.gamemode.other:
    default: op
  alsace.commands.time:
    default: op
  alsace.commands.time.other:
    default: op
  alsace.commands.weather:
    default: op
  alsace.commands.ptime:
    default: op
  alsace.commands.ptime.other:
    default: op
  alsace.protect.place:
    default: op
  alsace.protect.break:
    default: op
  alsace.protect.interact:
    default: op